name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    runs-on: ubuntu-latest
    name: Tests with python
    steps:
      - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install isort
      
      - name: Sort imports
        run: |
          isort $(git diff --name-only --diff-filter=ACMRTUXB origin/master | grep  -E \"(.py$)\")"
