name: Linters

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort --only-modified .
      - name: Commit changes
        run: |
          echo ${{ github.ref_namehead_ref }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m 'isort'
          git pull --rebase
          git push ${{ github.head_ref }}
